# Generated by Django 5.2 on 2025-04-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comptebancaire",
            name="numero_compte",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
