# Generated by Django 5.2 on 2025-04-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_comptebancaire_numero_compte"),
    ]

    operations = [
        migrations.AddField(
            model_name="comptebancaire",
            name="commentaire_admin",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comptebancaire",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente d'approbation"),
                    ("approuve", "Approuvé"),
                    ("rejete", "Rejeté"),
                ],
                default="en_attente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="comptebancaire",
            name="numero_compte",
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comptebancaire",
            name="type_compte",
            field=models.CharField(
                choices=[("courant", "Compte Courant"), ("epargne", "Compte Épargne")],
                max_length=20,
            ),
        ),
    ]
