# Generated by Django 5.2 on 2025-04-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_comptebancaire_commentaire_admin_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comptebancaire",
            name="commentaire_admin",
        ),
        migrations.AlterField(
            model_name="comptebancaire",
            name="numero_compte",
            field=models.CharField(default=0, max_length=20, unique=True),
        ),
    ]
