# Generated by Django 5.2 on 2025-04-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_comptebancaire_numero_compte"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("succès", "Succès"),
                    ("échoué", "Échoué"),
                    ("en_attente", "En attente"),
                ],
                max_length=10,
            ),
        ),
    ]
