# Generated by Django 5.2 on 2025-04-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_transaction_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="commentaire",
            field=models.TextField(blank=True, null=True),
        ),
    ]
