# Generated by Django 5.2 on 2025-04-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_transaction_commentaire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="compte_destination",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
