# Generated by Django 5.2 on 2025-04-24 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_transaction_compte_destination"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="compte_destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions_destination",
                to="api.comptebancaire",
            ),
        ),
    ]
